name: CI

on: 
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ] 
  workflow_dispatch:  
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:        
        python-version: 3.7      
    - name: Install dependencies
      run: |         
        python -m pip install --upgrade pip         
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort        
        pip install -r api_yamdb/requirements.txt 
    - name: Test with flake8 and django tests
      env:
          SECRET_KEY: ${{ secrets.YAMDB_SECRET_KEY }}
      run: |        
        python -m flake8        
        
        python api_yamdb/manage.py test        
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo        
        uses: actions/checkout@v2    
      - name: Login to Docker         
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Push to Docker Hub        
        uses: docker/build-push-action@v2 
        with:
          context: ./api_yamdb
          file: ./api_yamdb/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/api_yamdb:latest 
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands to deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd ~/yamdb_final
          git pull
          cd infra
          docker-compose stop
          docker-compose up -d --build
          docker exec infra_web_1 python manage.py makemigrations users
          docker exec infra_web_1 python manage.py makemigrations reviews
          docker exec infra_web_1 python manage.py migrate
